### ISSUE TITLE
Todo's for figures

### ISSUE THREAD

**Issue by tdrose** [tdrose/metaspace_analysis#6]
The following things need to be worked on for the figures:

- [x] 4A&F: reorder to Brain, Kidney, Lung
- [x] Consistent use of '*' throughout all plots
- [x] Decrease point size in 2K
- [x] 2H: improve visibility of overlapping text/bar (and supplement)
- [x] Update all formulas from `C39H79N2O6P+H` to `[C39H79N2O6P+H]+`
- [x] Look up all formulas for mentioned molecules, to put them in the figure captions.
- [x] Single pixel Brain: Better consistent colorscheme, Improve plot H such that it adds more value to the figure.

**Comment by tdrose** [comment]
The only remaining part is to assemble the new main figure.

**Comment by tdrose** [comment]
Done.
